import Footer from "@/components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PostLayout({ children }) {
  return (
    <main>
      {children}
      <Footer />
    </main>
  );
}
