import Footer from "@/components/Footer";
import { Separator } from "@/components/ui/separator";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PostLayout({ children }) {
  return (
    <main>
      {children}
      <Separator />
      <Footer />
    </main>
  );
}
